/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVistas;

import CapaLogica.ManejoDeUsuarios;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class BajasUsuarios extends javax.swing.JInternalFrame {
             ManejoDeUsuarios objm = new ManejoDeUsuarios();
     String path=null;
    /**
     * Creates new form BajasUsuarios
     */
    public BajasUsuarios() {
        initComponents();
        MostrarTablaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtiddeusuario = new javax.swing.JTextField();
        jtxtnombre = new javax.swing.JTextField();
        jtxtapellidos = new javax.swing.JTextField();
        jtxtpassword = new javax.swing.JTextField();
        jtxtcorreo = new javax.swing.JTextField();
        jtxtgenero = new javax.swing.JTextField();
        jtxtdomicilio = new javax.swing.JTextField();
        jtxttelefono = new javax.swing.JTextField();
        jtxttipodeusuario = new javax.swing.JTextField();
        jtxtfoto = new javax.swing.JTextField();
        jbtneliminar = new javax.swing.JButton();
        jbtncancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jbtnactualizar = new javax.swing.JButton();

        setTitle("BAJAS USUARIOS");

        jbtneliminar.setText("Eliminar");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });

        jbtncancelar.setText("Cancelar");

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtUsuarios);

        jbtnactualizar.setText("Actualizar tabla");
        jbtnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jtxtapellidos)
                            .addComponent(jtxtiddeusuario))
                        .addGap(379, 379, 379)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jtxtcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtfoto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxttipodeusuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtdomicilio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtgenero, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtiddeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jtxtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtncancelar))
                .addGap(18, 18, 18)
                .addComponent(jtxtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnactualizar))
                .addGap(18, 18, 18)
                .addComponent(jtxtdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxttipodeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jtxtfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        int idusuario=Integer.parseInt(jtxtiddeusuario.getText());
        int flag=objm.DarBajasUsuarios(idusuario);
        
        try {
            if(flag==1){
            JOptionPane.showMessageDialog(null, "Usuario eliminado");
        }if(flag==0){
            JOptionPane.showMessageDialog(null, "Usuario no eliminado");
        }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jtUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuariosMouseClicked
        int selecionar=jtUsuarios.rowAtPoint(evt.getPoint());
        jtxtiddeusuario.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 0)));
        jtxtnombre.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 1)));
        jtxtapellidos.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 2)));
        jtxtpassword.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 3)));
        jtxtcorreo.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 4)));
        jtxtgenero.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 5)));
        jtxttelefono.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 6)));
        jtxtdomicilio.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 7)));
        jtxttipodeusuario.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 8)));
        jtxtfoto.setText(String.valueOf(jtUsuarios.getValueAt(selecionar, 9)));
    }//GEN-LAST:event_jtUsuariosMouseClicked

    private void jbtnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnactualizarActionPerformed
        MostrarTablaUsuarios();
    }//GEN-LAST:event_jbtnactualizarActionPerformed
     public void MostrarTablaUsuarios(){
            DefaultTableModel modelo=new DefaultTableModel();
            ResultSet rs=objm.TablaUsuarios(); 
            String[] columnas={"IdUsuarios","Nombre","Apellidos","Password","Email","Genero","Telefono","Domicilio","TipoDeUsuario","Foto"};
            
               
            modelo.setColumnIdentifiers(columnas);
            try {
                  while(rs.next()){
                    modelo.addRow(new Object[]{rs.getString("idusuario"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("password"),rs.getString("email"),rs.getString("genero"),rs.getString("telefono"),
                        rs.getString("domicilio"),rs.getString("tipodeusuario"),rs.getString("foto")
                    });
                  }
                  jtUsuarios.setModel(modelo);
                    
            } catch (Exception e) {
            }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnactualizar;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JTextField jtxtapellidos;
    private javax.swing.JTextField jtxtcorreo;
    private javax.swing.JTextField jtxtdomicilio;
    private javax.swing.JTextField jtxtfoto;
    private javax.swing.JTextField jtxtgenero;
    private javax.swing.JTextField jtxtiddeusuario;
    private javax.swing.JTextField jtxtnombre;
    private javax.swing.JTextField jtxtpassword;
    private javax.swing.JTextField jtxttelefono;
    private javax.swing.JTextField jtxttipodeusuario;
    // End of variables declaration//GEN-END:variables
}
