/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jlbletiNombre = new javax.swing.JLabel();
        jbtnEsquina = new javax.swing.JButton();
        jbtnCentro = new javax.swing.JButton();
        jbtnAgrandar = new javax.swing.JButton();
        jbtnAchicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica_6_del_Parcial_2");

        jlbletiNombre.setBackground(new java.awt.Color(0, 153, 153));
        jlbletiNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbletiNombre.setForeground(new java.awt.Color(51, 51, 51));
        jlbletiNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbletiNombre.setText("VICTOR MANUEL GALVAN COVARRUBIAS");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jlbletiNombre, org.jdesktop.beansbinding.ELProperty.create("true"), jlbletiNombre, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        jbtnEsquina.setText("Esquina");
        jbtnEsquina.setPreferredSize(new java.awt.Dimension(80, 25));
        jbtnEsquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnEsquinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnEsquinaMouseExited(evt);
            }
        });
        jbtnEsquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEsquinaActionPerformed(evt);
            }
        });

        jbtnCentro.setText("Centro");
        jbtnCentro.setPreferredSize(new java.awt.Dimension(80, 25));
        jbtnCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnCentroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCentroMouseExited(evt);
            }
        });
        jbtnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCentroActionPerformed(evt);
            }
        });

        jbtnAgrandar.setText("Agrandar");
        jbtnAgrandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAgrandarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAgrandarMouseExited(evt);
            }
        });
        jbtnAgrandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgrandarActionPerformed(evt);
            }
        });

        jbtnAchicar.setText("Achicar");
        jbtnAchicar.setPreferredSize(new java.awt.Dimension(80, 25));
        jbtnAchicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnAchicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnAchicarMouseExited(evt);
            }
        });
        jbtnAchicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAchicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jbtnEsquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jbtnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jbtnAgrandar)
                        .addGap(69, 69, 69)
                        .addComponent(jbtnAchicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbletiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jlbletiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAgrandar)
                    .addComponent(jbtnEsquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAchicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCentroActionPerformed
        jlbletiNombre.setLocation(173,219);
    }//GEN-LAST:event_jbtnCentroActionPerformed

    private void jbtnEsquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEsquinaActionPerformed
        jlbletiNombre.setLocation(0,0);
    }//GEN-LAST:event_jbtnEsquinaActionPerformed

    private void jbtnAgrandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgrandarActionPerformed
        jlbletiNombre.setSize(400,100);
    }//GEN-LAST:event_jbtnAgrandarActionPerformed

    private void jbtnAchicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAchicarActionPerformed
        jlbletiNombre.setSize(272,15);
    }//GEN-LAST:event_jbtnAchicarActionPerformed

    private void jbtnEsquinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEsquinaMouseExited
        jbtnEsquina.setSize(80,25);
    }//GEN-LAST:event_jbtnEsquinaMouseExited

    private void jbtnEsquinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEsquinaMouseEntered
        jbtnEsquina.setSize(100,40);
    }//GEN-LAST:event_jbtnEsquinaMouseEntered

    private void jbtnCentroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCentroMouseEntered
       jbtnCentro.setSize(100,40);
    }//GEN-LAST:event_jbtnCentroMouseEntered

    private void jbtnCentroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCentroMouseExited
        jbtnCentro.setSize(80,25);
    }//GEN-LAST:event_jbtnCentroMouseExited

    private void jbtnAgrandarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgrandarMouseEntered
        jbtnAgrandar.setSize(100,40);
    }//GEN-LAST:event_jbtnAgrandarMouseEntered

    private void jbtnAgrandarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAgrandarMouseExited
        jbtnAgrandar.setSize(80,25);
    }//GEN-LAST:event_jbtnAgrandarMouseExited

    private void jbtnAchicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAchicarMouseEntered
        jbtnAchicar.setSize(100,40);
    }//GEN-LAST:event_jbtnAchicarMouseEntered

    private void jbtnAchicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAchicarMouseExited
        jbtnAchicar.setSize(80, 25);
    }//GEN-LAST:event_jbtnAchicarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAchicar;
    private javax.swing.JButton jbtnAgrandar;
    private javax.swing.JButton jbtnCentro;
    private javax.swing.JButton jbtnEsquina;
    private javax.swing.JLabel jlbletiNombre;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
