/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Logica.AritmeticaLog;

public class Aritmetica extends javax.swing.JFrame {
    AritmeticaLog objL= new AritmeticaLog();
    /**
     * Creates new form Aritmetica
     */
    public Aritmetica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jtxtresultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtnum1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtnum2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnmultiplicar = new javax.swing.JButton();
        jbtndividir = new javax.swing.JButton();
        jbtnrestar = new javax.swing.JButton();
        jbtnsumar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jugando con numeros");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);

        jLabel4.setText("RESULTADO");

        jtxtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtresultadoActionPerformed(evt);
            }
        });

        jLabel3.setText("NUMERO 2");

        jtxtnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnum1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Jugando con numeros");

        jtxtnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnum2ActionPerformed(evt);
            }
        });

        jLabel2.setText("NUMERO 1");

        jbtnmultiplicar.setText("MULTIPLICAR");
        jbtnmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplicarActionPerformed(evt);
            }
        });

        jbtndividir.setText("DIVIDIR");
        jbtndividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndividirActionPerformed(evt);
            }
        });

        jbtnrestar.setText("RESTAR");
        jbtnrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrestarActionPerformed(evt);
            }
        });

        jbtnsumar.setText("SUMAR");
        jbtnsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jtxtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(238, 238, 238))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtndividir)
                                .addComponent(jbtnmultiplicar)
                                .addComponent(jbtnrestar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbtnsumar)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(121, 121, 121)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtxtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(jtxtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(186, 186, 186)
                                            .addComponent(jLabel3)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnsumar)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnrestar)
                    .addComponent(jtxtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnmultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtndividir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnum1ActionPerformed

    private void jbtndividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndividirActionPerformed
        int num1=Integer.parseInt(jtxtnum1.getText());
        int num2=Integer.parseInt(jtxtnum2.getText());      
        int resultado=objL.Dividir(num1, num2);
        jtxtresultado.setText(resultado+"");
    }//GEN-LAST:event_jbtndividirActionPerformed

    private void jbtnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumarActionPerformed
        int num1=Integer.parseInt(jtxtnum1.getText());
        int num2=Integer.parseInt(jtxtnum2.getText());      
        int resultado=objL.Sumar(num1, num2);
        jtxtresultado.setText(resultado+"");
    }//GEN-LAST:event_jbtnsumarActionPerformed

    private void jbtnmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplicarActionPerformed
        int num1=Integer.parseInt(jtxtnum1.getText());
        int num2=Integer.parseInt(jtxtnum2.getText());      
        int resultado=objL.Multiplicar(num1, num2);
        jtxtresultado.setText(resultado+"");
    }//GEN-LAST:event_jbtnmultiplicarActionPerformed

    private void jbtnrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestarActionPerformed
        int num1=Integer.parseInt(jtxtnum1.getText());
        int num2=Integer.parseInt(jtxtnum2.getText());      
        int resultado=objL.Restar(num1, num2);
        jtxtresultado.setText(resultado+"");
    }//GEN-LAST:event_jbtnrestarActionPerformed

    private void jtxtnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnum2ActionPerformed

    private void jtxtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtresultadoActionPerformed
       
    }//GEN-LAST:event_jtxtresultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmetica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtndividir;
    private javax.swing.JButton jbtnmultiplicar;
    private javax.swing.JButton jbtnrestar;
    private javax.swing.JButton jbtnsumar;
    private javax.swing.JTextField jtxtnum1;
    private javax.swing.JTextField jtxtnum2;
    private javax.swing.JTextField jtxtresultado;
    // End of variables declaration//GEN-END:variables
}
