/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jlbletiPal1 = new javax.swing.JLabel();
        jlbletiPal2 = new javax.swing.JLabel();
        jlbletiPal3 = new javax.swing.JLabel();
        jlbletiPal4 = new javax.swing.JLabel();
        jlbletiOcultar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica_5_del_Parcial_2");
        setBackground(new java.awt.Color(0, 0, 0));

        jlbletiPal1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbletiPal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbletiPal1.setText("UNO");

        jlbletiPal2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbletiPal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbletiPal2.setText("DOS");

        jlbletiPal3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbletiPal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbletiPal3.setText("TRES");

        jlbletiPal4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbletiPal4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbletiPal4.setText("CUATRO");

        jlbletiOcultar.setBackground(new java.awt.Color(0, 102, 102));
        jlbletiOcultar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlbletiOcultar.setForeground(new java.awt.Color(0, 0, 0));
        jlbletiOcultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbletiOcultar.setText("Ocultar");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jlbletiOcultar, org.jdesktop.beansbinding.ELProperty.create("true"), jlbletiOcultar, org.jdesktop.beansbinding.BeanProperty.create("opaque"));
        bindingGroup.addBinding(binding);

        jlbletiOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbletiOcultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbletiOcultarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbletiOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlbletiPal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbletiPal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbletiPal3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbletiPal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jlbletiOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlbletiPal1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbletiPal2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbletiPal3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jlbletiPal4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbletiOcultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbletiOcultarMouseEntered
        jlbletiPal1.setVisible(false);
        jlbletiPal2.setVisible(false);
        jlbletiPal3.setVisible(false);
        jlbletiPal4.setVisible(false);
    }//GEN-LAST:event_jlbletiOcultarMouseEntered

    private void jlbletiOcultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbletiOcultarMouseExited
        jlbletiPal1.setVisible(true);
        jlbletiPal2.setVisible(true);
        jlbletiPal3.setVisible(true);
        jlbletiPal4.setVisible(true);
    }//GEN-LAST:event_jlbletiOcultarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbletiOcultar;
    private javax.swing.JLabel jlbletiPal1;
    private javax.swing.JLabel jlbletiPal2;
    private javax.swing.JLabel jlbletiPal3;
    private javax.swing.JLabel jlbletiPal4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
