
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbletiTexto = new javax.swing.JLabel();
        jbtnFondoAzul = new javax.swing.JButton();
        jbtnFondoRojo = new javax.swing.JButton();
        jbtnFondoVerde = new javax.swing.JButton();
        jbtnTransparente = new javax.swing.JButton();
        jbtnOpaca = new javax.swing.JButton();
        jbtnAzul = new javax.swing.JButton();
        jbtnVerde = new javax.swing.JButton();
        jbtnRojo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica_7_del_Parcial_2");

        jlbletiTexto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlbletiTexto.setText("Interstellar");

        jbtnFondoAzul.setText("Fondo Azul");
        jbtnFondoAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFondoAzulActionPerformed(evt);
            }
        });

        jbtnFondoRojo.setText("Fondo Rojo");
        jbtnFondoRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFondoRojoActionPerformed(evt);
            }
        });

        jbtnFondoVerde.setText("Fondo Verde");
        jbtnFondoVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFondoVerdeActionPerformed(evt);
            }
        });

        jbtnTransparente.setText("Transparente");
        jbtnTransparente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransparenteActionPerformed(evt);
            }
        });

        jbtnOpaca.setText("Opaca");
        jbtnOpaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpacaActionPerformed(evt);
            }
        });

        jbtnAzul.setText("Azul");
        jbtnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAzulActionPerformed(evt);
            }
        });

        jbtnVerde.setText("Verde");
        jbtnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVerdeActionPerformed(evt);
            }
        });

        jbtnRojo.setText("Rojo");
        jbtnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRojoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbtnFondoAzul)
                            .addComponent(jbtnFondoRojo)
                            .addComponent(jbtnFondoVerde)
                            .addComponent(jbtnTransparente))
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbtnVerde)
                            .addComponent(jbtnRojo)
                            .addComponent(jbtnOpaca)
                            .addComponent(jbtnAzul)))
                    .addComponent(jlbletiTexto))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlbletiTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnFondoAzul)
                    .addComponent(jbtnAzul))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnFondoRojo)
                    .addComponent(jbtnRojo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnFondoVerde))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jbtnVerde)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTransparente)
                    .addComponent(jbtnOpaca))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnFondoAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFondoAzulActionPerformed
        jlbletiTexto.setBackground(Color.BLUE);
    }//GEN-LAST:event_jbtnFondoAzulActionPerformed

    private void jbtnFondoRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFondoRojoActionPerformed
        jlbletiTexto.setBackground(Color.RED);
    }//GEN-LAST:event_jbtnFondoRojoActionPerformed

    private void jbtnFondoVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFondoVerdeActionPerformed
        jlbletiTexto.setBackground(Color.GREEN);
    }//GEN-LAST:event_jbtnFondoVerdeActionPerformed

    private void jbtnTransparenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransparenteActionPerformed
        jlbletiTexto.setOpaque(false);
    }//GEN-LAST:event_jbtnTransparenteActionPerformed

    private void jbtnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAzulActionPerformed
        jlbletiTexto.setForeground(Color.BLUE);
    }//GEN-LAST:event_jbtnAzulActionPerformed

    private void jbtnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRojoActionPerformed
        jlbletiTexto.setForeground(Color.RED);
    }//GEN-LAST:event_jbtnRojoActionPerformed

    private void jbtnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVerdeActionPerformed
        jlbletiTexto.setForeground(Color.GREEN);
    }//GEN-LAST:event_jbtnVerdeActionPerformed

    private void jbtnOpacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpacaActionPerformed
        jlbletiTexto.setOpaque(true);
    }//GEN-LAST:event_jbtnOpacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAzul;
    private javax.swing.JButton jbtnFondoAzul;
    private javax.swing.JButton jbtnFondoRojo;
    private javax.swing.JButton jbtnFondoVerde;
    private javax.swing.JButton jbtnOpaca;
    private javax.swing.JButton jbtnRojo;
    private javax.swing.JButton jbtnTransparente;
    private javax.swing.JButton jbtnVerde;
    private javax.swing.JLabel jlbletiTexto;
    // End of variables declaration//GEN-END:variables
}
